plugins:
  - jekyll-remote-theme

remote_theme: ngzhio/jekyll-theme-hamilton


title: tech35 Home Page
googleanalytics: G-DQR34FWC30

author: "tech35"

email: "asgharbilawal6@gmail.com"

skin: "daylight"

paginate: "2"

avatar: "https://avatars.githubusercontent.com/u/72114077?s=460&u=6885cbc86505a2968e5ab04d635a95e3a8ad2de0&v=4"

disqus: "https://tech35.disqus.com/about/"
